SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR arm)

SET(CMAKE_C_COMPILER "arm-openipc-linux-musleabi-gcc")
SET(CMAKE_CXX_COMPILER "arm-openipc-linux-musleabi-g++")
SET(CMAKE_FIND_ROOT_PATH /home/builder/builds/openipc/extsdk)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)